(function(){
 const cfg=window.APP_CONFIG||{}; const valid=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('PASTE_')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('PASTE_');
 const loginCard=document.getElementById('login-card'),editor=document.getElementById('editor-card'),loginMsg=document.getElementById('login-msg');
 if(!valid||!window.supabase){loginMsg.className='msg err';loginMsg.textContent='config.js-এ নতুন Supabase তথ্য বসান।';return}
 const client=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY); const adminEmail=(cfg.ADMIN_EMAIL||'').toLowerCase();
 const nf=[['khatian','খতিয়ান নং'],['owner','মালিক'],['dag_no','দাগ নং'],['survey','সার্ভে'],['mouza','মৌজা'],['upazila','উপজেলা'],['district','জেলা'],['division','বিভাগ'],['record_date','তারিখ']];
 const nfBox=document.getElementById('normal-fields'); nf.forEach(([k,l])=>nfBox.insertAdjacentHTML('beforeend',`<label>${l}<input id="f_${k}"></label>`));
 function msg(el,t,ok){el.textContent=t;el.className='msg '+(ok?'ok':'err')}
 function normalUrl(id){return location.origin+location.pathname.replace('admin.html','index.html')+'?id='+encodeURIComponent(id)}
 async function loadNormal(){const body=document.getElementById('normal-history');body.innerHTML='';const {data,error}=await client.from('land_records').select('*').order('id',{ascending:false});if(error)return msg(document.getElementById('save-msg'),error.message,false);(data||[]).forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${r.id}</td><td>${r.khatian??''}</td><td>${r.owner??''}</td><td>${r.dag_no??''}</td><td>${r.mouza??''}</td><td><a href="${normalUrl(r.id)}" target="_blank">দেখুন</a></td><td><button data-id="${r.id}" class="del-normal">ডিলেট</button></td>`;body.appendChild(tr)});body.querySelectorAll('.del-normal').forEach(b=>b.onclick=async()=>{if(!confirm('এই খতিয়ানটি ডিলেট করবেন?'))return;const {error:e}=await client.from('land_records').delete().eq('id',Number(b.dataset.id));if(e)alert(e.message);await loadNormal()})}
 async function loadReady(){const body=document.getElementById('ready-history');body.innerHTML='';const {data,error}=await client.from('ready_khatian').select('id,title,owner_name,mouja,created_at').order('id',{ascending:false});if(error){body.innerHTML=`<tr><td colspan="6">${error.message}</td></tr>`;return}(data||[]).forEach(r=>{const u=location.origin+location.pathname.replace('admin.html','ready-khatian-view.html')+'?id='+r.id;const tr=document.createElement('tr');tr.innerHTML=`<td>${r.id}</td><td>${r.title??''}</td><td>${r.owner_name??''}</td><td>${r.mouja??''}</td><td><a href="${u}" target="_blank">দেখুন</a></td><td><button class="del-ready" data-id="${r.id}">ডিলেট</button></td>`;body.appendChild(tr)});body.querySelectorAll('.del-ready').forEach(b=>b.onclick=async()=>{if(!confirm('এই রেডি খতিয়ানটি ডিলেট করবেন?'))return;const {error:e}=await client.from('ready_khatian').delete().eq('id',Number(b.dataset.id));if(e)alert(e.message);await loadReady()})}
 async function enter(session){if(!session)return;const e=(session.user.email||'').toLowerCase();if(adminEmail&&e!==adminEmail){await client.auth.signOut();msg(loginMsg,'এই ইমেইলটি অনুমোদিত নয়।',false);return}loginCard.style.display='none';editor.style.display='block';loadNormal();loadReady()}
 client.auth.getSession().then(r=>enter(r.data.session)); document.getElementById('login').onclick=async()=>{const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;const {data,error}=await client.auth.signInWithPassword({email,password});if(error)return msg(loginMsg,error.message,false);enter(data.session)};
 document.getElementById('save-normal').onclick=async()=>{const row={};for(const [k] of nf){const v=document.getElementById('f_'+k).value.trim();if(!v)return msg(document.getElementById('save-msg'),'সবগুলো ঘর পূরণ করুন।',false);row[k]=v}const {error}=await client.from('land_records').insert(row);if(error)return msg(document.getElementById('save-msg'),error.message,false);msg(document.getElementById('save-msg'),'✅ নতুন খতিয়ান সংযুক্ত হয়েছে।',true);nf.forEach(([k])=>document.getElementById('f_'+k).value='');loadNormal()};
 document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById(t.dataset.tab+'-tab').classList.add('active');if(t.dataset.tab==='ready')loadReady()});
 document.getElementById('logout').onclick=async()=>{await client.auth.signOut();location.reload()};
})();
