-- নতুন Supabase project-এর SQL Editor-এ এই পুরো ফাইল একবার চালান।
create table if not exists public.land_records (
  id bigint generated by default as identity primary key,
  khatian text not null, owner text not null, dag_no text not null, survey text not null,
  mouza text not null, upazila text not null, district text not null, division text not null,
  record_date text not null, created_at timestamptz not null default now()
);

create table if not exists public.ready_khatian (
  id bigint generated by default as identity primary key,
  title text not null,
  division text, district text, upazila text, mouza text, jl_no text, record_no text,
  owner_address text, share text, revenue text, dag text, agri text, non_agri text,
  dag_unit text, dag_percent text, record_share text, area_unit text, area_percent text,
  remarks text, note1 text, note2 text, note3 text, total_unit text, total_percent text,
  print_date text, form_no text, page_no text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.land_records enable row level security;
alter table public.ready_khatian enable row level security;

drop policy if exists "land_records_public_read" on public.land_records;
create policy "land_records_public_read" on public.land_records for select using (true);
drop policy if exists "ready_khatian_public_read" on public.ready_khatian;
create policy "ready_khatian_public_read" on public.ready_khatian for select using (is_deleted = false);

drop policy if exists "ready_khatian_auth_insert" on public.ready_khatian;
create policy "ready_khatian_auth_insert" on public.ready_khatian for insert to authenticated with check (true);
drop policy if exists "ready_khatian_auth_delete" on public.ready_khatian;
create policy "ready_khatian_auth_delete" on public.ready_khatian for delete to authenticated using (true);

drop policy if exists "land_records_auth_write" on public.land_records;
create policy "land_records_auth_write" on public.land_records for all to authenticated using (true) with check (true);
